# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/cost_graph.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.CostGraphDef" do
    repeated :node, :message, 1, "tensorflow.CostGraphDef.Node"
  end
  add_message "tensorflow.CostGraphDef.Node" do
    optional :name, :string, 1
    optional :device, :string, 2
    optional :id, :int32, 3
    repeated :input_info, :message, 4, "tensorflow.CostGraphDef.Node.InputInfo"
    repeated :output_info, :message, 5, "tensorflow.CostGraphDef.Node.OutputInfo"
    optional :temporary_memory_size, :int64, 6
    optional :is_final, :bool, 7
    repeated :control_input, :int32, 8
  end
  add_message "tensorflow.CostGraphDef.Node.InputInfo" do
    optional :preceding_node, :int32, 1
    optional :preceding_port, :int32, 2
  end
  add_message "tensorflow.CostGraphDef.Node.OutputInfo" do
    optional :size, :int64, 1
    optional :alias_input_port, :int64, 2
  end
end

module Tensorflow
  CostGraphDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef").msgclass
  CostGraphDef::Node = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef.Node").msgclass
  CostGraphDef::Node::InputInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef.Node.InputInfo").msgclass
  CostGraphDef::Node::OutputInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CostGraphDef.Node.OutputInfo").msgclass
end
