# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/kernel_def.proto

require 'google/protobuf'

require 'tensorflow/core/framework/attr_value'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.KernelDef" do
    optional :op, :string, 1
    optional :device_type, :string, 2
    repeated :constraint, :message, 3, "tensorflow.KernelDef.AttrConstraint"
    repeated :host_memory_arg, :string, 4
    optional :label, :string, 5
  end
  add_message "tensorflow.KernelDef.AttrConstraint" do
    optional :name, :string, 1
    optional :allowed_values, :message, 2, "tensorflow.AttrValue"
  end
end

module Tensorflow
  KernelDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.KernelDef").msgclass
  KernelDef::AttrConstraint = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.KernelDef.AttrConstraint").msgclass
end
