# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/log_memory.proto

require 'google/protobuf'

require 'tensorflow/core/framework/tensor_description'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.MemoryLogStep" do
    optional :step_id, :int64, 1
    optional :handle, :string, 2
  end
  add_message "tensorflow.MemoryLogTensorAllocation" do
    optional :step_id, :int64, 1
    optional :kernel_name, :string, 2
    optional :tensor, :message, 3, "tensorflow.TensorDescription"
  end
  add_message "tensorflow.MemoryLogTensorDeallocation" do
    optional :allocation_id, :int64, 1
    optional :allocator_name, :string, 2
  end
  add_message "tensorflow.MemoryLogTensorOutput" do
    optional :step_id, :int64, 1
    optional :kernel_name, :string, 2
    optional :index, :int32, 3
    optional :tensor, :message, 4, "tensorflow.TensorDescription"
  end
  add_message "tensorflow.MemoryLogRawAllocation" do
    optional :step_id, :int64, 1
    optional :operation, :string, 2
    optional :num_bytes, :int64, 3
    optional :ptr, :uint64, 4
    optional :allocation_id, :int64, 5
    optional :allocator_name, :string, 6
  end
  add_message "tensorflow.MemoryLogRawDeallocation" do
    optional :step_id, :int64, 1
    optional :operation, :string, 2
    optional :allocation_id, :int64, 3
    optional :allocator_name, :string, 4
    optional :deferred, :bool, 5
  end
end

module Tensorflow
  MemoryLogStep = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryLogStep").msgclass
  MemoryLogTensorAllocation = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryLogTensorAllocation").msgclass
  MemoryLogTensorDeallocation = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryLogTensorDeallocation").msgclass
  MemoryLogTensorOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryLogTensorOutput").msgclass
  MemoryLogRawAllocation = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryLogRawAllocation").msgclass
  MemoryLogRawDeallocation = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemoryLogRawDeallocation").msgclass
end
