# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/step_stats.proto

require 'google/protobuf'

require 'tensorflow/core/framework/allocation_description'
require 'tensorflow/core/framework/tensor_description'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.AllocatorMemoryUsed" do
    optional :allocator_name, :string, 1
    optional :total_bytes, :int64, 2
    optional :peak_bytes, :int64, 3
  end
  add_message "tensorflow.NodeOutput" do
    optional :slot, :int32, 1
    optional :tensor_description, :message, 3, "tensorflow.TensorDescription"
  end
  add_message "tensorflow.NodeExecStats" do
    optional :node_name, :string, 1
    optional :all_start_micros, :int64, 2
    optional :op_start_rel_micros, :int64, 3
    optional :op_end_rel_micros, :int64, 4
    optional :all_end_rel_micros, :int64, 5
    repeated :memory, :message, 6, "tensorflow.AllocatorMemoryUsed"
    repeated :output, :message, 7, "tensorflow.NodeOutput"
    optional :timeline_label, :string, 8
    optional :scheduled_micros, :int64, 9
    optional :thread_id, :uint32, 10
    repeated :referenced_tensor, :message, 11, "tensorflow.AllocationDescription"
  end
  add_message "tensorflow.DeviceStepStats" do
    optional :device, :string, 1
    repeated :node_stats, :message, 2, "tensorflow.NodeExecStats"
  end
  add_message "tensorflow.StepStats" do
    repeated :dev_stats, :message, 1, "tensorflow.DeviceStepStats"
  end
end

module Tensorflow
  AllocatorMemoryUsed = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.AllocatorMemoryUsed").msgclass
  NodeOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NodeOutput").msgclass
  NodeExecStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.NodeExecStats").msgclass
  DeviceStepStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeviceStepStats").msgclass
  StepStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.StepStats").msgclass
end
