# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/tensor_slice.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.TensorSliceProto" do
    repeated :extent, :message, 1, "tensorflow.TensorSliceProto.Extent"
  end
  add_message "tensorflow.TensorSliceProto.Extent" do
    optional :start, :int64, 1
    oneof :has_length do
      optional :length, :int64, 2
    end
  end
end

module Tensorflow
  TensorSliceProto = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorSliceProto").msgclass
  TensorSliceProto::Extent = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorSliceProto.Extent").msgclass
end
