# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/tensor.proto

require 'google/protobuf'

require 'tensorflow/core/framework/tensor_shape'
require 'tensorflow/core/framework/types'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.TensorProto" do
    optional :dtype, :enum, 1, "tensorflow.DataType"
    optional :tensor_shape, :message, 2, "tensorflow.TensorShapeProto"
    optional :version_number, :int32, 3
    optional :tensor_content, :bytes, 4
    repeated :half_val, :int32, 13
    repeated :float_val, :float, 5
    repeated :double_val, :double, 6
    repeated :int_val, :int32, 7
    repeated :string_val, :bytes, 8
    repeated :scomplex_val, :float, 9
    repeated :int64_val, :int64, 10
    repeated :bool_val, :bool, 11
    repeated :dcomplex_val, :double, 12
  end
end

module Tensorflow
  TensorProto = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorProto").msgclass
end
