#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/example/feature.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class Example < ::ProtocolBuffers::Message; end
  class SequenceExample < ::ProtocolBuffers::Message; end

  class Example < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.Example"

    optional ::Tensorflow::Features, :features, 1
  end

  class SequenceExample < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.SequenceExample"

    optional ::Tensorflow::Features, :context, 1
    optional ::Tensorflow::FeatureLists, :feature_lists, 2
  end

end
