# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/example/feature.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.BytesList" do
    repeated :value, :bytes, 1
  end
  add_message "tensorflow.FloatList" do
    repeated :value, :float, 1
  end
  add_message "tensorflow.Int64List" do
    repeated :value, :int64, 1
  end
  add_message "tensorflow.Feature" do
    oneof :kind do
      optional :bytes_list, :message, 1, "tensorflow.BytesList"
      optional :float_list, :message, 2, "tensorflow.FloatList"
      optional :int64_list, :message, 3, "tensorflow.Int64List"
    end
  end
  add_message "tensorflow.Features" do
    map :feature, :string, :message, 1, "tensorflow.Feature"
  end
  add_message "tensorflow.FeatureList" do
    repeated :feature, :message, 1, "tensorflow.Feature"
  end
  add_message "tensorflow.FeatureLists" do
    map :feature_list, :string, :message, 1, "tensorflow.FeatureList"
  end
end

module Tensorflow
  BytesList = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.BytesList").msgclass
  FloatList = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FloatList").msgclass
  Int64List = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.Int64List").msgclass
  Feature = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.Feature").msgclass
  Features = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.Features").msgclass
  FeatureList = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FeatureList").msgclass
  FeatureLists = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.FeatureLists").msgclass
end
