#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class ReaderBaseState < ::ProtocolBuffers::Message; end

  class ReaderBaseState < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ReaderBaseState"

    optional :int64, :work_started, 1
    optional :int64, :work_finished, 2
    optional :int64, :num_records_produced, 3
    optional :bytes, :current_work, 4
  end

end
