# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/queue_runner.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.QueueRunnerDef" do
    optional :queue_name, :string, 1
    repeated :enqueue_op_name, :string, 2
    optional :close_op_name, :string, 3
    optional :cancel_op_name, :string, 4
  end
end

module Tensorflow
  QueueRunnerDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.QueueRunnerDef").msgclass
end
