# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/worker_service.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/worker'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Tensorflow
  module Grpc
  end
end
