require 'tensorflow/core/framework/tensor'
require 'tensorflow/core/framework/graph'
require 'sciruby/Tensorflow'
require 'narray'
require 'tensorflow/tensor'
require 'tensorflow/graph'
require 'tensorflow/session'
