#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class AllocationDescription < ::ProtocolBuffers::Message; end

  class AllocationDescription < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.AllocationDescription"

    optional :int64, :requested_bytes, 1
    optional :int64, :allocated_bytes, 2
    optional :string, :allocator_name, 3
    optional :int64, :allocation_id, 4
    optional :bool, :has_single_reference, 5
    optional :uint64, :ptr, 6
  end

end
