#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/tensor.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/tensor_shape.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/types.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class AttrValue < ::ProtocolBuffers::Message; end
  class NameAttrList < ::ProtocolBuffers::Message; end

  class AttrValue < ::ProtocolBuffers::Message
    # forward declarations
    class ListValue < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.AttrValue"

    # nested messages
    class ListValue < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.AttrValue.ListValue"

      repeated :bytes, :s, 2
      repeated :int64, :i, 3, :packed => true 
      repeated :float, :f, 4, :packed => true 
      repeated :bool, :b, 5, :packed => true 
      repeated ::Tensorflow::DataType, :type, 6, :packed => true 
      repeated ::Tensorflow::TensorShapeProto, :shape, 7
      repeated ::Tensorflow::TensorProto, :tensor, 8
    end

    optional :bytes, :s, 2
    optional :int64, :i, 3
    optional :float, :f, 4
    optional :bool, :b, 5
    optional ::Tensorflow::DataType, :type, 6
    optional ::Tensorflow::TensorShapeProto, :shape, 7
    optional ::Tensorflow::TensorProto, :tensor, 8
    optional ::Tensorflow::AttrValue::ListValue, :list, 1
    optional ::Tensorflow::NameAttrList, :func, 10
    optional :string, :placeholder, 9
  end

  class NameAttrList < ::ProtocolBuffers::Message
    # forward declarations
    class AttrEntry < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.NameAttrList"

    # nested messages
    class AttrEntry < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.NameAttrList.AttrEntry"

      optional :string, :key, 1
      optional ::Tensorflow::AttrValue, :value, 2
    end

    optional :string, :name, 1
    repeated ::Tensorflow::NameAttrList::AttrEntry, :attr, 2
  end

end
