#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class CostGraphDef < ::ProtocolBuffers::Message; end

  class CostGraphDef < ::ProtocolBuffers::Message
    # forward declarations
    class Node < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.CostGraphDef"

    # nested messages
    class Node < ::ProtocolBuffers::Message
      # forward declarations
      class InputInfo < ::ProtocolBuffers::Message; end
      class OutputInfo < ::ProtocolBuffers::Message; end

      set_fully_qualified_name "tensorflow.CostGraphDef.Node"

      # nested messages
      class InputInfo < ::ProtocolBuffers::Message
        set_fully_qualified_name "tensorflow.CostGraphDef.Node.InputInfo"

        optional :int32, :preceding_node, 1
        optional :int32, :preceding_port, 2
      end

      class OutputInfo < ::ProtocolBuffers::Message
        set_fully_qualified_name "tensorflow.CostGraphDef.Node.OutputInfo"

        optional :int64, :size, 1
        optional :int64, :alias_input_port, 2
      end

      optional :string, :name, 1
      optional :string, :device, 2
      optional :int32, :id, 3
      repeated ::Tensorflow::CostGraphDef::Node::InputInfo, :input_info, 4
      repeated ::Tensorflow::CostGraphDef::Node::OutputInfo, :output_info, 5
      optional :int64, :temporary_memory_size, 6
      optional :bool, :is_final, 7
      repeated :int32, :control_input, 8
    end

    repeated ::Tensorflow::CostGraphDef::Node, :node, 1
  end

end
