#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class DeviceAttributes < ::ProtocolBuffers::Message; end

  # enums
  module BusAdjacency
    include ::ProtocolBuffers::Enum

    set_fully_qualified_name "tensorflow.BusAdjacency"

    BUS_0 = 0
    BUS_1 = 1
    BUS_ANY = 2
    BUS_NUM_ADJACENCIES = 3
  end

  class DeviceAttributes < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.DeviceAttributes"

    optional :string, :name, 1
    optional :string, :device_type, 2
    optional :int64, :memory_limit, 4
    optional ::Tensorflow::BusAdjacency, :bus_adjacency, 5
    optional :fixed64, :incarnation, 6
    optional :string, :physical_device_desc, 7
  end

end
