# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/device_attributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.DeviceAttributes" do
    optional :name, :string, 1
    optional :device_type, :string, 2
    optional :memory_limit, :int64, 4
    optional :bus_adjacency, :enum, 5, "tensorflow.BusAdjacency"
    optional :incarnation, :fixed64, 6
    optional :physical_device_desc, :string, 7
  end
  add_enum "tensorflow.BusAdjacency" do
    value :BUS_0, 0
    value :BUS_1, 1
    value :BUS_ANY, 2
    value :BUS_NUM_ADJACENCIES, 3
  end
end

module Tensorflow
  DeviceAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.DeviceAttributes").msgclass
  BusAdjacency = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.BusAdjacency").enummodule
end
