#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/attr_value.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/op_def.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class FunctionDefLibrary < ::ProtocolBuffers::Message; end
  class FunctionDef < ::ProtocolBuffers::Message; end
  class GradientDef < ::ProtocolBuffers::Message; end

  class FunctionDefLibrary < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.FunctionDefLibrary"

    repeated ::Tensorflow::FunctionDef, :function, 1
    repeated ::Tensorflow::GradientDef, :gradient, 2
  end

  class FunctionDef < ::ProtocolBuffers::Message
    # forward declarations
    class Node < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.FunctionDef"

    # nested messages
    class Node < ::ProtocolBuffers::Message
      # forward declarations
      class AttrEntry < ::ProtocolBuffers::Message; end

      set_fully_qualified_name "tensorflow.FunctionDef.Node"

      # nested messages
      class AttrEntry < ::ProtocolBuffers::Message
        set_fully_qualified_name "tensorflow.FunctionDef.Node.AttrEntry"

        optional :string, :key, 1
        optional ::Tensorflow::AttrValue, :value, 2
      end

      repeated :string, :ret, 1
      optional :string, :op, 2
      repeated :string, :arg, 3
      repeated :string, :dep, 4
      repeated ::Tensorflow::FunctionDef::Node::AttrEntry, :attr, 5
    end

    optional ::Tensorflow::OpDef, :signature, 1
    repeated ::Tensorflow::FunctionDef::Node, :node, 2
  end

  class GradientDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.GradientDef"

    optional :string, :function_name, 1
    optional :string, :gradient_func, 2
  end

end
