#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/attr_value.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/function.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/versions.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class GraphDef < ::ProtocolBuffers::Message; end
  class NodeDef < ::ProtocolBuffers::Message; end

  class GraphDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.GraphDef"

    repeated ::Tensorflow::NodeDef, :node, 1
    optional ::Tensorflow::VersionDef, :versions, 4
    optional :int32, :version, 3
    optional ::Tensorflow::FunctionDefLibrary, :library, 2
  end

  class NodeDef < ::ProtocolBuffers::Message
    # forward declarations
    class AttrEntry < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.NodeDef"

    # nested messages
    class AttrEntry < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.NodeDef.AttrEntry"

      optional :string, :key, 1
      optional ::Tensorflow::AttrValue, :value, 2
    end

    optional :string, :name, 1
    optional :string, :op, 2
    repeated :string, :input, 3
    optional :string, :device, 4
    repeated ::Tensorflow::NodeDef::AttrEntry, :attr, 5
  end

end
