#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/attr_value.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class KernelDef < ::ProtocolBuffers::Message; end

  class KernelDef < ::ProtocolBuffers::Message
    # forward declarations
    class AttrConstraint < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.KernelDef"

    # nested messages
    class AttrConstraint < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.KernelDef.AttrConstraint"

      optional :string, :name, 1
      optional ::Tensorflow::AttrValue, :allowed_values, 2
    end

    optional :string, :op, 1
    optional :string, :device_type, 2
    repeated ::Tensorflow::KernelDef::AttrConstraint, :constraint, 3
    repeated :string, :host_memory_arg, 4
    optional :string, :label, 5
  end

end
