#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/tensor_description.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class MemoryLogStep < ::ProtocolBuffers::Message; end
  class MemoryLogTensorAllocation < ::ProtocolBuffers::Message; end
  class MemoryLogTensorDeallocation < ::ProtocolBuffers::Message; end
  class MemoryLogTensorOutput < ::ProtocolBuffers::Message; end
  class MemoryLogRawAllocation < ::ProtocolBuffers::Message; end
  class MemoryLogRawDeallocation < ::ProtocolBuffers::Message; end

  class MemoryLogStep < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryLogStep"

    optional :int64, :step_id, 1
    optional :string, :handle, 2
  end

  class MemoryLogTensorAllocation < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryLogTensorAllocation"

    optional :int64, :step_id, 1
    optional :string, :kernel_name, 2
    optional ::Tensorflow::TensorDescription, :tensor, 3
  end

  class MemoryLogTensorDeallocation < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryLogTensorDeallocation"

    optional :int64, :allocation_id, 1
    optional :string, :allocator_name, 2
  end

  class MemoryLogTensorOutput < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryLogTensorOutput"

    optional :int64, :step_id, 1
    optional :string, :kernel_name, 2
    optional :int32, :index, 3
    optional ::Tensorflow::TensorDescription, :tensor, 4
  end

  class MemoryLogRawAllocation < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryLogRawAllocation"

    optional :int64, :step_id, 1
    optional :string, :operation, 2
    optional :int64, :num_bytes, 3
    optional :uint64, :ptr, 4
    optional :int64, :allocation_id, 5
    optional :string, :allocator_name, 6
  end

  class MemoryLogRawDeallocation < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryLogRawDeallocation"

    optional :int64, :step_id, 1
    optional :string, :operation, 2
    optional :int64, :allocation_id, 3
    optional :string, :allocator_name, 4
    optional :bool, :deferred, 5
  end

end
