#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class TensorShapeProto < ::ProtocolBuffers::Message; end

  class TensorShapeProto < ::ProtocolBuffers::Message
    # forward declarations
    class Dim < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.TensorShapeProto"

    # nested messages
    class Dim < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.TensorShapeProto.Dim"

      optional :int64, :size, 1
      optional :string, :name, 2
    end

    repeated ::Tensorflow::TensorShapeProto::Dim, :dim, 2
    optional :bool, :unknown_rank, 3
  end

end
