#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class TensorSliceProto < ::ProtocolBuffers::Message; end

  class TensorSliceProto < ::ProtocolBuffers::Message
    # forward declarations
    class Extent < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.TensorSliceProto"

    # nested messages
    class Extent < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.TensorSliceProto.Extent"

      optional :int64, :start, 1
      optional :int64, :length, 2
    end

    repeated ::Tensorflow::TensorSliceProto::Extent, :extent, 1
  end

end
