#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/tensor_shape.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/types.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class TensorProto < ::ProtocolBuffers::Message; end

  class TensorProto < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.TensorProto"

    optional ::Tensorflow::DataType, :dtype, 1
    optional ::Tensorflow::TensorShapeProto, :tensor_shape, 2
    optional :int32, :version_number, 3
    optional :bytes, :tensor_content, 4
    repeated :int32, :half_val, 13, :packed => true 
    repeated :float, :float_val, 5, :packed => true 
    repeated :double, :double_val, 6, :packed => true 
    repeated :int32, :int_val, 7, :packed => true 
    repeated :bytes, :string_val, 8
    repeated :float, :scomplex_val, 9, :packed => true 
    repeated :int64, :int64_val, 10, :packed => true 
    repeated :bool, :bool_val, 11, :packed => true 
    repeated :double, :dcomplex_val, 12, :packed => true 
  end

end
