#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/types.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/tensor_shape.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/allocation_description.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class TensorDescription < ::ProtocolBuffers::Message; end

  class TensorDescription < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.TensorDescription"

    optional ::Tensorflow::DataType, :dtype, 1
    optional ::Tensorflow::TensorShapeProto, :shape, 2
    optional ::Tensorflow::AllocationDescription, :allocation_description, 4
  end

end
