#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class VariableDef < ::ProtocolBuffers::Message; end
  class SaveSliceInfoDef < ::ProtocolBuffers::Message; end

  class VariableDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.VariableDef"

    optional :string, :variable_name, 1
    optional :string, :initializer_name, 2
    optional :string, :snapshot_name, 3
    optional ::Tensorflow::SaveSliceInfoDef, :save_slice_info_def, 4
  end

  class SaveSliceInfoDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.SaveSliceInfoDef"

    optional :string, :full_name, 1
    repeated :int32, :full_shape, 2
    repeated :int32, :var_offset, 3
    repeated :int32, :var_shape, 4
  end

end
