#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class VersionDef < ::ProtocolBuffers::Message; end

  class VersionDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.VersionDef"

    optional :int32, :producer, 1
    optional :int32, :min_consumer, 2
    repeated :int32, :bad_consumers, 3
  end

end
