# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/master.proto

require 'google/protobuf'

require 'tensorflow/core/framework/device_attributes'
require 'tensorflow/core/framework/graph'
require 'tensorflow/core/protobuf/config'
require 'tensorflow/core/protobuf/named_tensor'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.CreateSessionRequest" do
    optional :graph_def, :message, 1, "tensorflow.GraphDef"
    optional :config, :message, 2, "tensorflow.ConfigProto"
  end
  add_message "tensorflow.CreateSessionResponse" do
    optional :session_handle, :string, 1
    optional :graph_version, :int64, 2
  end
  add_message "tensorflow.ExtendSessionRequest" do
    optional :session_handle, :string, 1
    optional :graph_def, :message, 2, "tensorflow.GraphDef"
    optional :current_graph_version, :int64, 3
  end
  add_message "tensorflow.ExtendSessionResponse" do
    optional :new_graph_version, :int64, 4
  end
  add_message "tensorflow.RunStepRequest" do
    optional :session_handle, :string, 1
    repeated :feed, :message, 2, "tensorflow.NamedTensorProto"
    repeated :fetch, :string, 3
    repeated :target, :string, 4
    optional :options, :message, 5, "tensorflow.RunOptions"
  end
  add_message "tensorflow.RunStepResponse" do
    repeated :tensor, :message, 1, "tensorflow.NamedTensorProto"
    optional :metadata, :message, 2, "tensorflow.RunMetadata"
  end
  add_message "tensorflow.CloseSessionRequest" do
    optional :session_handle, :string, 1
  end
  add_message "tensorflow.CloseSessionResponse" do
  end
  add_message "tensorflow.ResetRequest" do
    repeated :container, :string, 1
  end
  add_message "tensorflow.ResetResponse" do
  end
  add_message "tensorflow.ListDevicesRequest" do
  end
  add_message "tensorflow.ListDevicesResponse" do
    repeated :local_device, :message, 1, "tensorflow.DeviceAttributes"
    repeated :remote_device, :message, 2, "tensorflow.DeviceAttributes"
  end
end

module Tensorflow
  CreateSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CreateSessionRequest").msgclass
  CreateSessionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CreateSessionResponse").msgclass
  ExtendSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ExtendSessionRequest").msgclass
  ExtendSessionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ExtendSessionResponse").msgclass
  RunStepRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunStepRequest").msgclass
  RunStepResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.RunStepResponse").msgclass
  CloseSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CloseSessionRequest").msgclass
  CloseSessionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.CloseSessionResponse").msgclass
  ResetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ResetRequest").msgclass
  ResetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ResetResponse").msgclass
  ListDevicesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ListDevicesRequest").msgclass
  ListDevicesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ListDevicesResponse").msgclass
end
