#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/device_attributes.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/graph.pb'; rescue LoadError; end
begin; require 'tensorflow/core/protobuf/config.pb'; rescue LoadError; end
begin; require 'tensorflow/core/protobuf/named_tensor.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class CreateSessionRequest < ::ProtocolBuffers::Message; end
  class CreateSessionResponse < ::ProtocolBuffers::Message; end
  class ExtendSessionRequest < ::ProtocolBuffers::Message; end
  class ExtendSessionResponse < ::ProtocolBuffers::Message; end
  class RunStepRequest < ::ProtocolBuffers::Message; end
  class RunStepResponse < ::ProtocolBuffers::Message; end
  class CloseSessionRequest < ::ProtocolBuffers::Message; end
  class CloseSessionResponse < ::ProtocolBuffers::Message; end
  class ResetRequest < ::ProtocolBuffers::Message; end
  class ResetResponse < ::ProtocolBuffers::Message; end
  class ListDevicesRequest < ::ProtocolBuffers::Message; end
  class ListDevicesResponse < ::ProtocolBuffers::Message; end

  class CreateSessionRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.CreateSessionRequest"

    optional ::Tensorflow::GraphDef, :graph_def, 1
    optional ::Tensorflow::ConfigProto, :config, 2
  end

  class CreateSessionResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.CreateSessionResponse"

    optional :string, :session_handle, 1
    optional :int64, :graph_version, 2
  end

  class ExtendSessionRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ExtendSessionRequest"

    optional :string, :session_handle, 1
    optional ::Tensorflow::GraphDef, :graph_def, 2
    optional :int64, :current_graph_version, 3
  end

  class ExtendSessionResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ExtendSessionResponse"

    optional :int64, :new_graph_version, 4
  end

  class RunStepRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.RunStepRequest"

    optional :string, :session_handle, 1
    repeated ::Tensorflow::NamedTensorProto, :feed, 2
    repeated :string, :fetch, 3
    repeated :string, :target, 4
    optional ::Tensorflow::RunOptions, :options, 5
  end

  class RunStepResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.RunStepResponse"

    repeated ::Tensorflow::NamedTensorProto, :tensor, 1
    optional ::Tensorflow::RunMetadata, :metadata, 2
  end

  class CloseSessionRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.CloseSessionRequest"

    optional :string, :session_handle, 1
  end

  class CloseSessionResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.CloseSessionResponse"

  end

  class ResetRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ResetRequest"

    repeated :string, :container, 1
  end

  class ResetResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ResetResponse"

  end

  class ListDevicesRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ListDevicesRequest"

  end

  class ListDevicesResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.ListDevicesResponse"

    repeated ::Tensorflow::DeviceAttributes, :local_device, 1
    repeated ::Tensorflow::DeviceAttributes, :remote_device, 2
  end

end
