#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'google/protobuf/any.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/graph.pb'; rescue LoadError; end
begin; require 'tensorflow/core/framework/op_def.pb'; rescue LoadError; end
begin; require 'tensorflow/core/protobuf/saver.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class MetaGraphDef < ::ProtocolBuffers::Message; end
  class CollectionDef < ::ProtocolBuffers::Message; end

  class MetaGraphDef < ::ProtocolBuffers::Message
    # forward declarations
    class MetaInfoDef < ::ProtocolBuffers::Message; end
    class CollectionDefEntry < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.MetaGraphDef"

    # nested messages
    class MetaInfoDef < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.MetaGraphDef.MetaInfoDef"

      optional :string, :meta_graph_version, 1
      optional ::Tensorflow::OpList, :stripped_op_list, 2
      optional ::Google::Protobuf::Any, :any_info, 3
    end

    class CollectionDefEntry < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.MetaGraphDef.CollectionDefEntry"

      optional :string, :key, 1
      optional ::Tensorflow::CollectionDef, :value, 2
    end

    optional ::Tensorflow::MetaGraphDef::MetaInfoDef, :meta_info_def, 1
    optional ::Tensorflow::GraphDef, :graph_def, 2
    optional ::Tensorflow::SaverDef, :saver_def, 3
    repeated ::Tensorflow::MetaGraphDef::CollectionDefEntry, :collection_def, 4
  end

  class CollectionDef < ::ProtocolBuffers::Message
    # forward declarations
    class NodeList < ::ProtocolBuffers::Message; end
    class BytesList < ::ProtocolBuffers::Message; end
    class Int64List < ::ProtocolBuffers::Message; end
    class FloatList < ::ProtocolBuffers::Message; end
    class AnyList < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.CollectionDef"

    # nested messages
    class NodeList < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.CollectionDef.NodeList"

      repeated :string, :value, 1
    end

    class BytesList < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.CollectionDef.BytesList"

      repeated :bytes, :value, 1
    end

    class Int64List < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.CollectionDef.Int64List"

      repeated :int64, :value, 1, :packed => true 
    end

    class FloatList < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.CollectionDef.FloatList"

      repeated :float, :value, 1, :packed => true 
    end

    class AnyList < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.CollectionDef.AnyList"

      repeated ::Google::Protobuf::Any, :value, 1
    end

    optional ::Tensorflow::CollectionDef::NodeList, :node_list, 1
    optional ::Tensorflow::CollectionDef::BytesList, :bytes_list, 2
    optional ::Tensorflow::CollectionDef::Int64List, :int64_list, 3
    optional ::Tensorflow::CollectionDef::FloatList, :float_list, 4
    optional ::Tensorflow::CollectionDef::AnyList, :any_list, 5
  end

end
