#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/framework/tensor.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class NamedTensorProto < ::ProtocolBuffers::Message; end

  class NamedTensorProto < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.NamedTensorProto"

    optional :string, :name, 1
    optional ::Tensorflow::TensorProto, :tensor, 2
  end

end
