#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class QueueRunnerDef < ::ProtocolBuffers::Message; end

  class QueueRunnerDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.QueueRunnerDef"

    optional :string, :queue_name, 1
    repeated :string, :enqueue_op_name, 2
    optional :string, :close_op_name, 3
    optional :string, :cancel_op_name, 4
  end

end
