#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class SaverDef < ::ProtocolBuffers::Message; end

  class SaverDef < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.SaverDef"

    optional :string, :filename_tensor_name, 1
    optional :string, :save_tensor_name, 2
    optional :string, :restore_op_name, 3
    optional :int32, :max_to_keep, 4
    optional :bool, :sharded, 5
    optional :float, :keep_checkpoint_every_n_hours, 6
  end

end
