# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/tensorflow_server.proto

require 'google/protobuf'

require 'tensorflow/core/protobuf/config'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.JobDef" do
    optional :name, :string, 1
    map :tasks, :int32, :string, 2
  end
  add_message "tensorflow.ClusterDef" do
    repeated :job, :message, 1, "tensorflow.JobDef"
  end
  add_message "tensorflow.ServerDef" do
    optional :cluster, :message, 1, "tensorflow.ClusterDef"
    optional :job_name, :string, 2
    optional :task_index, :int32, 3
    optional :default_session_config, :message, 4, "tensorflow.ConfigProto"
    optional :protocol, :string, 5
  end
end

module Tensorflow
  JobDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.JobDef").msgclass
  ClusterDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ClusterDef").msgclass
  ServerDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ServerDef").msgclass
end
