#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'tensorflow/core/protobuf/worker.pb'; rescue LoadError; end

module Tensorflow
  module Grpc
    class WorkerService < ::ProtocolBuffers::Service
      set_fully_qualified_name "tensorflow.grpc.WorkerService"

      rpc :get_status, "GetStatus", ::Tensorflow::GetStatusRequest, ::Tensorflow::GetStatusResponse
      rpc :register_graph, "RegisterGraph", ::Tensorflow::RegisterGraphRequest, ::Tensorflow::RegisterGraphResponse
      rpc :deregister_graph, "DeregisterGraph", ::Tensorflow::DeregisterGraphRequest, ::Tensorflow::DeregisterGraphResponse
      rpc :run_graph, "RunGraph", ::Tensorflow::RunGraphRequest, ::Tensorflow::RunGraphResponse
      rpc :cleanup_graph, "CleanupGraph", ::Tensorflow::CleanupGraphRequest, ::Tensorflow::CleanupGraphResponse
      rpc :cleanup_all, "CleanupAll", ::Tensorflow::CleanupAllRequest, ::Tensorflow::CleanupAllResponse
      rpc :recv_tensor, "RecvTensor", ::Tensorflow::RecvTensorRequest, ::Tensorflow::RecvTensorResponse
      rpc :logging, "Logging", ::Tensorflow::LoggingRequest, ::Tensorflow::LoggingResponse
      rpc :tracing, "Tracing", ::Tensorflow::TracingRequest, ::Tensorflow::TracingResponse
    end
  end
end
