# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/util/memmapped_file_system.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.MemmappedFileSystemDirectoryElement" do
    optional :offset, :uint64, 1
    optional :name, :string, 2
  end
  add_message "tensorflow.MemmappedFileSystemDirectory" do
    repeated :element, :message, 1, "tensorflow.MemmappedFileSystemDirectoryElement"
  end
end

module Tensorflow
  MemmappedFileSystemDirectoryElement = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemmappedFileSystemDirectoryElement").msgclass
  MemmappedFileSystemDirectory = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.MemmappedFileSystemDirectory").msgclass
end
