#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tensorflow
  # forward declarations
  class MemmappedFileSystemDirectoryElement < ::ProtocolBuffers::Message; end
  class MemmappedFileSystemDirectory < ::ProtocolBuffers::Message; end

  class MemmappedFileSystemDirectoryElement < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemmappedFileSystemDirectoryElement"

    optional :uint64, :offset, 1
    optional :string, :name, 2
  end

  class MemmappedFileSystemDirectory < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemmappedFileSystemDirectory"

    repeated ::Tensorflow::MemmappedFileSystemDirectoryElement, :element, 1
  end

end
