#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'google/protobuf/any.pb'; rescue LoadError; end

module Tensorflow
  # forward declarations
  class EntryValue < ::ProtocolBuffers::Message; end
  class BenchmarkEntry < ::ProtocolBuffers::Message; end
  class BenchmarkEntries < ::ProtocolBuffers::Message; end
  class BuildConfiguration < ::ProtocolBuffers::Message; end
  class CommitId < ::ProtocolBuffers::Message; end
  class CPUInfo < ::ProtocolBuffers::Message; end
  class MemoryInfo < ::ProtocolBuffers::Message; end
  class GPUInfo < ::ProtocolBuffers::Message; end
  class PlatformInfo < ::ProtocolBuffers::Message; end
  class AvailableDeviceInfo < ::ProtocolBuffers::Message; end
  class MachineConfiguration < ::ProtocolBuffers::Message; end
  class RunConfiguration < ::ProtocolBuffers::Message; end
  class TestResults < ::ProtocolBuffers::Message; end

  class EntryValue < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.EntryValue"

    optional :double, :double_value, 1
    optional :string, :string_value, 2
  end

  class BenchmarkEntry < ::ProtocolBuffers::Message
    # forward declarations
    class ExtrasEntry < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.BenchmarkEntry"

    # nested messages
    class ExtrasEntry < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.BenchmarkEntry.ExtrasEntry"

      optional :string, :key, 1
      optional ::Tensorflow::EntryValue, :value, 2
    end

    optional :string, :name, 1
    optional :int64, :iters, 2
    optional :double, :cpu_time, 3
    optional :double, :wall_time, 4
    optional :double, :throughput, 5
    repeated ::Tensorflow::BenchmarkEntry::ExtrasEntry, :extras, 6
  end

  class BenchmarkEntries < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.BenchmarkEntries"

    repeated ::Tensorflow::BenchmarkEntry, :entry, 1
  end

  class BuildConfiguration < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.BuildConfiguration"

    optional :string, :mode, 1
    repeated :string, :cc_flags, 2
    repeated :string, :opts, 3
  end

  class CommitId < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.CommitId"

    optional :int64, :changelist, 1
    optional :string, :hash, 2
    optional :string, :snapshot, 3
  end

  class CPUInfo < ::ProtocolBuffers::Message
    # forward declarations
    class CacheSizeEntry < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "tensorflow.CPUInfo"

    # nested messages
    class CacheSizeEntry < ::ProtocolBuffers::Message
      set_fully_qualified_name "tensorflow.CPUInfo.CacheSizeEntry"

      optional :string, :key, 1
      optional :int64, :value, 2
    end

    optional :int64, :num_cores, 1
    optional :int64, :num_cores_allowed, 2
    optional :double, :mhz_per_cpu, 3
    optional :string, :cpu_info, 4
    optional :string, :cpu_governor, 5
    repeated ::Tensorflow::CPUInfo::CacheSizeEntry, :cache_size, 6
  end

  class MemoryInfo < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MemoryInfo"

    optional :int64, :total, 1
    optional :int64, :available, 2
  end

  class GPUInfo < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.GPUInfo"

    optional :string, :model, 1
    optional :string, :uuid, 2
    optional :string, :bus_id, 3
  end

  class PlatformInfo < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.PlatformInfo"

    optional :string, :bits, 1
    optional :string, :linkage, 2
    optional :string, :machine, 3
    optional :string, :release, 4
    optional :string, :system, 5
    optional :string, :version, 6
  end

  class AvailableDeviceInfo < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.AvailableDeviceInfo"

    optional :string, :name, 1
    optional :string, :type, 2
    optional :int64, :memory_limit, 3
    optional :string, :physical_description, 4
  end

  class MachineConfiguration < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.MachineConfiguration"

    optional :string, :hostname, 1
    optional :string, :serial_identifier, 7
    optional ::Tensorflow::PlatformInfo, :platform_info, 2
    optional ::Tensorflow::CPUInfo, :cpu_info, 3
    repeated ::Google::Protobuf::Any, :device_info, 4
    repeated ::Tensorflow::AvailableDeviceInfo, :available_device_info, 5
    optional ::Tensorflow::MemoryInfo, :memory_info, 6
  end

  class RunConfiguration < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.RunConfiguration"

    repeated :string, :argument, 1
  end

  class TestResults < ::ProtocolBuffers::Message
    set_fully_qualified_name "tensorflow.TestResults"

    optional :string, :target, 1
    optional ::Tensorflow::BenchmarkEntries, :entries, 2
    optional ::Tensorflow::BuildConfiguration, :build_configuration, 3
    optional ::Tensorflow::CommitId, :commit_id, 4
    optional :int64, :start_time, 5
    optional :double, :run_time, 6
    optional ::Tensorflow::MachineConfiguration, :machine_configuration, 7
    optional ::Tensorflow::RunConfiguration, :run_configuration, 8
  end

end
