# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/kernels/reader_base.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.ReaderBaseState" do
    optional :work_started, :int64, 1
    optional :work_finished, :int64, 2
    optional :num_records_produced, :int64, 3
    optional :current_work, :bytes, 4
  end
end

module Tensorflow
  ReaderBaseState = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.ReaderBaseState").msgclass
end
